# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  image: latest

python:
  version: "3.11"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - gha
